### ISSUE TITLE
AgRenSeq

### ISSUE THREAD

**Issue by duhuipeng** [steuernb/AgRenSeq#2]
Why not have the  AgRenSeq_CreatePresenceMatrix.jar, I can not
 find it in src
hope answer the question

**Comment by steuernb** [comment]
Jar files are in the latest release
https://github.com/steuernb/AgRenSeq/releases/

**Comment by duhuipeng** [comment]
thank you,I am very appreciated for you

**Comment by duhuipeng** [comment]
java.io.FileNotFoundException: accessions.txt (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at commandLineInterface.AgRenSeq_CreateMatrix.main(AgRenSeq_CreateMatrix.java:54)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

I have the accession.txt files, but the mistakes always exist.I don't know how to make it

**Comment by duhuipeng** [comment]
java -jar AgRenSeq_CreatePresenceMatrix.jar -i accession.txt -o AgRenSeq_k51_presencematrix.txt -t 3 -n 10
The one above is my command code. however, it's made a mistake as follow.
java.lang.ArrayIndexOutOfBoundsException: 1
        at commandLineInterface.AgRenSeq_CreateMatrix.main(AgRenSeq_CreateMatrix.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
hope answer the question

**Comment by steuernb** [comment]
The ArrayIndexOutOfBoundsException could come from a wrong separator in the accessions.txt.
As it is now, it will only accept a tab separator. Any chance, that solves it?

**Comment by duhuipeng** [comment]
thank you ,The problem has been solved,I am very appreciated for you

**Comment by duhuipeng** [comment]
Follow your advice,  it's also made a mistake as follow  
java -jar AgRenSeq_CreatePresenceMatrix.jar -i accession.txt -o AgRenSeq_k51_presencematrix.txt -t 3 -n 10(Input command)
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession1.dump.txt
        finished reading accession1.dump.txt. Found 0 problems. Size of data: 2790
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession2.dump.txt
        finished reading accession2.dump.txt. Found 0 problems. Size of data: 9675883
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession3.dump.txt
        finished reading accession3.dump.txt. Found 0 problems. Size of data: 10855197
java.lang.ArrayIndexOutOfBoundsException: 1
        at commandLineInterface.AgRenSeq_CreateMatrix.main(AgRenSeq_CreateMatrix.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
(Show the results)
I looked at the generated file and there was nothing,I am very puzzled

**Comment by steuernb** [comment]
Hi, you still get the ArrayIndexOutOfBoundsException in line 62. This is within a loop, reading line by line through accession.txt. It is very happy with the first 3 lines. In the fourth line, there is either no tab separator or no text after the first tab. 
The size of your data in accession1 looks also very small. I guess, that there is something wrong. Then, if you have -t 3 (kmer must be present in at least three accessions), you will not have much output.

**Comment by duhuipeng** [comment]
I still have this problem. I want to send a picture about the code for you.I don't know what to do . Do you have wechat?I would like to have a further communication with you on the code step, my wechat is Dhp940818, I  hope you can agree

**Comment by steuernb** [comment]
I am not working in that group anymore where AgRenSeq has been developed. You probably get best help if you contact the corresponding author of the paper. If you post your accession.txt here I can still have a look what is going wrong with this particular step of the pipeline.

**Comment by duhuipeng** [comment]
I downloaded the process of three individuals to run,Is it because my individual data is too small because of the above reason?I'm going to download 20 individual data and try again.Do you feel like it can solve this problem?

**Comment by duhuipeng** [comment]
java -jar AgRenSeq_CreatePresenceMatrix.jar -i accession.txt -o AgRenSeq_k51_presencematrix.txt -t 3 -n 10     or       java -jar AgRenSeq_CreatePresenceMatrix.jar -i accession.txt -o ./AgRenSeq_k51_presencematrix.txt -t 3 -n 10
The one above is my command code
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession2.dump.txt
        finished reading accession2.dump.txt. Found 0 problems. Size of data: 9675843
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession3.dump.txt
        finished reading accession3.dump.txt. Found 0 problems. Size of data: 10855157
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession6.dump.txt
        finished reading accession6.dump.txt. Found 0 problems. Size of data: 13700852
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession10.dump.txt
        finished reading accession10.dump.txt. Found 0 problems. Size of data: 15222557
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession13.dump.txt
        finished reading accession13.dump.txt. Found 0 problems. Size of data: 17508120
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession14.dump.txt
        finished reading accession14.dump.txt. Found 0 problems. Size of data: 18778615
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession15.dump.txt
        finished reading accession15.dump.txt. Found 0 problems. Size of data: 19469245
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession19.dump.txt
        finished reading accession19.dump.txt. Found 0 problems. Size of data: 20891927
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession20.dump.txt
        finished reading accession20.dump.txt. Found 0 problems. Size of data: 21714367
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession21.dump.txt
        finished reading accession21.dump.txt. Found 0 problems. Size of data: 21979623
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession24.dump.txt
        finished reading accession24.dump.txt. Found 0 problems. Size of data: 22484776
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession25.dump.txt
        finished reading accession25.dump.txt. Found 0 problems. Size of data: 23268070
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession33.dump.txt
        finished reading accession33.dump.txt. Found 0 problems. Size of data: 23679513
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession36.dump.txt
        finished reading accession36.dump.txt. Found 0 problems. Size of data: 24729058
reading /home/Duhuipeng/DHP/database/AgRenSeq_CreateMatrix/accession38.dump.txt
        finished reading accession38.dump.txt. Found 0 problems. Size of data: 25481635
java.lang.ArrayIndexOutOfBoundsException: 0
        at commandLineInterface.AgRenSeq_CreateMatrix.main(AgRenSeq_CreateMatrix.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
AgRenSeq_CreateMatrix version 1.0-i <metainfofile>
-o <outputFile>
-t <threshold> kmers present in less than <t> or all but <t> will not be recorded.
-n <minimum kmer count>
The above is the result of the output after the run.Why I can't see my output file in the current directory.

**Comment by steuernb** [comment]
Can you please attach the file accessions.txt?

**Comment by duhuipeng** [comment]
[accession.txt](https://github.com/steuernb/AgRenSeq/files/3977426/accession.txt)

**Comment by steuernb** [comment]
Thanks! Line 16 has a tab character. Can you try removing line number 16?
[accession.txt](https://github.com/steuernb/AgRenSeq/files/3977440/accession.txt)

**Comment by duhuipeng** [comment]
how to remove line number 16,I don't understand

**Comment by duhuipeng** [comment]
![WeChat0ee06aa04602bbb0d25dfcd58fba7af4](https://user-images.githubusercontent.com/58722433/71071285-4646d380-21b7-11ea-8c9c-2bdad5aa4052.png)

**Comment by steuernb** [comment]
try running with the file I attached. In your file, you have a tab character in the line under the one with accession38. Unfortunately, this is interpreted as the accession "" with the path "".

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/71071487-adfd1e80-21b7-11ea-920f-58c571493c74.png)
is this the same after the deletion?

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/71072586-cc641980-21b9-11ea-9dd7-ecc41861605e.png)
In your way, I ran out,Thank you very much for solving the problem I haven't dealt with for three weeks

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/71086377-c29bdf80-21d4-11ea-87df-a313393e3a0b.png)
I'd like to know how this transformation score was structured. I didn't find this method code

**Comment by steuernb** [comment]
Trial and error. This one works nicely for stem rust. For other systems, you might want to change it.

**Comment by duhuipeng** [comment]
I just built the missing matrix, now I want to build the phenotypic file, I'm running with the data you provide, I downloaded a small part, but I don't know how to construct this phenotypic file, I can't find the location of the code, I want to know where the transformation model can be found, I can't find the website.

**Comment by steuernb** [comment]
Please have a look at the paper again. In there you will find that the step you are starting now has been improved  and is described here: https://github.com/kgaurav1208/AgRenSeq_GLM.

**Comment by duhuipeng** [comment]
I see that the software you use to assemble from scratch is expensive, so I can't go on now. I want to know how I assemble k-mer from scratch. I see that ABYSS can assemble k-mer from scratch, but he can only identify the format of fastq. What am I supposed to do?

**Comment by steuernb** [comment]
I had reasonable results with masurca. We have not tested it in this project so no promises but it should work.

**Comment by duhuipeng** [comment]
Can you provide a source of code for this Masurca software? I'm stuck in this process now. I can't go on.

**Comment by steuernb** [comment]
http://www.genome.umd.edu/masurca.html
It has been a while since I used it. You will have to figure it out yourself. Or give ABYSS a go.

**Comment by duhuipeng** [comment]
If I'm going to use abyss, do you know how to convert k-mer to fastq, can I continue to use your code for a follow-up process

**Comment by steuernb** [comment]
You would do the de novo assembly with ABYSS on the fastq data of that accession you chose. You had fastq in the first place before you extracted kmers. The idea is to project the kmer matrix you created onto a de novo assembly of a resistant accession. Doing so, you will see signals on the contigs of your resistance gene. 

If you continue using the pipeline on this github account you run AgRenSeq without regarding population structure. You will get some of the target genes but not all of them. I would recommend using AgRenSeq_GLM

**Comment by duhuipeng** [comment]
I'm beginning to assemble every accession, so how can I get RenSeq about the R gene, and Should I assemble all the accession from scratch into a total output file?

**Comment by duhuipeng** [comment]
I really want to add your WeChat, want to have a further communication with you, can you give a chance to be in scientific research and white exchange, this is my WeChat:Dhp940818, I sincerely hope you can add me, no matter whether you agree, you are very grateful for this time to answer my question


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Burkhard Steuernagel"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 晚上8:39
收件人:&nbsp;"steuernb/AgRenSeq"<AgRenSeq@noreply.github.com&gt;;
抄送:&nbsp;"七匹狼"<1561857525@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [steuernb/AgRenSeq] AgRenSeq (#2)




I had reasonable results with masurca. We have not tested it in this project so no promises but it should work.

**Comment by steuernb** [comment]
I feel like the level of support you need is beyond the pipeline in this repository. I urge you again to contact the corresponding author of the paper. If you are seeking a collaboration it should be with him.

**Comment by duhuipeng** [comment]
I'm still a student, don't seek cooperation, just want to run this process, I'm using ABTYSS to run a try, thank you very much for your answers, do not understand that through this platform in time to communicate with you.

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/71235275-a9ab3f80-2336-11ea-8326-fd095cb44f5e.png)
I have made a de novo assembly of the accession2 and accsessions 3, and the output results are again assembled, as shown in the figure above,
I want to use NLR-parser for non-fragment filtering now, but I can't find this jar file. I'd like to ask where I can find it.
![image](https://user-images.githubusercontent.com/58722433/71235880-66ea6700-2338-11ea-8ae9-3de8b4cfcb48.png)

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/71255735-bf862800-2369-11ea-810b-f75712cb36f3.png)
Why can't I get out of the bin under this path after I download it?,(As shown below)no matter what I am root or not root
![image](https://user-images.githubusercontent.com/58722433/71256040-a2058e00-236a-11ea-8741-e89dfa0a61dd.png)

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/71308163-f1fc5780-2433-11ea-8da1-4152cdda0609.png)
I finished the seventh step, because I assembled the ABYSS software from the walk. I don't know if the result of the seventh step is in the same form as the file content output by the CLC software you provided.
At the same time, I have a software  AgRenSeq_RunAssociation.jar that's not found, can I have a link to this software?

**Comment by duhuipeng** [comment]
java -jar AgRenSeq_RunAssociation.jar -i prenseceMatrix -p phenotype -o AgRenSeqResult.txt
Can I and p in this step make the txt file I generated above?

**Comment by duhuipeng** [comment]
I want to know what went wrong with me. I came in this forma
![image](https://user-images.githubusercontent.com/58722433/71308718-e06a7e00-243a-11ea-9cdc-da350eb8d083.png)

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/71309113-17429300-243f-11ea-943b-7b9f42a4ad20.png)
I don't know what's wrong with me. Can you help me? I can't think of it. It's stuck here again.

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/71316540-cae16c80-24ab-11ea-9a28-ffd5464cb18c.png)
I draw a picture like this. How does it feel strange? can you point out where there is a problem?

**Comment by laura45678** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/58722433/71309113-17429300-243f-11ea-943b-7b9f42a4ad20.png) I don't know what's wrong with me. Can you help me? I can't think of it. It's stuck here again.

Dear @duhuipeng,
when I run the AgRenSeq_RunAssociation.jar I am facing the same problem you had on Dec 21, 2019 (java.lang.NullPointerException). Do you remember how you solved it and would you tell me the solution?
I would be very grateful for an answer

**Comment by YFKIB** [comment]
> > ![image](https://user-images.githubusercontent.com/58722433/71309113-17429300-243f-11ea-943b-7b9f42a4ad20.png) I don't know what's wrong with me. Can you help me? I can't think of it. It's stuck here again.
> 
> Dear @duhuipeng, when I run the AgRenSeq_RunAssociation.jar I am facing the same problem you had on Dec 21, 2019 (java.lang.NullPointerException). Do you remember how you solved it and would you tell me the solution? I would be very grateful for an answer

You need to input the parameter nlr.txt, which is the result of the NLR-Parser，Can you add my WeChat? I stiil have some questions I want to discuss. My WeChat is fy1935107151。
